export const StdIoRequests = {
  REQUEST_RESTART 	: 'REQUEST_RESTART',
  REQUEST_EXIT			:	'REQUEST_EXIT',
  REQUEST_HARD_EXIT	: 'REQUEST_HARD_EXIT',
  REQUEST_STATUS		: 'REQUEST_STATUS',
  REQUEST_CLIENTS		: 'REQUEST_CLIENTS',
  REQUEST_ECHO			: 'REQUEST_ECHO',
}

export const StdIoEvents = {
  UPDATE_STATUS			: 'UPDATE_STATUS',
  UPDATE_ERROR			: 'UPDATE_ERROR',
  UPDATE_CLIENTS		: 'UPDATE_CLIENTS',
}

export const StdIoLogEvents = {
  CONSOLE:		'CONSOLE',
  INTERFACE: 	'INTERFACE',
}

export const StdIoResponseMapping = {
  REQUEST_RESTART 	: 'RESPONSE_RESTART',
  REQUEST_EXIT			:	'RESPONSE_EXIT',
  REQUEST_STATUS		: 'RESPONSE_STATUS',
  REQUEST_CLIENTS		: 'RESPONSE_CLIENTS',
  REQUEST_ECHO			: 'RESPONSE_ECHO',
}